### ISSUE TITLE
Is there a way to override the fields in BaseField at once?

### ISSUE THREAD

**Issue by vinodMS** [labd/wagtailstreamforms#126]
How do I override BaseField at once to include a new field ? I'm following the instructions [here](https://wagtailstreamforms.readthedocs.io/en/latest/fields.html?highlight=BaseField#setting-field-options) to add a new editable field option. But if I want to have new editable field added to all available fields, how do I go about doing this?

**Comment by stuartaccent** [comment]
Hi @vinodMS 

Unfortunately there is no way to override those base settings that I know of without overriding each field in your own file. Ensuring the wagtailstreamforms_fields.py lives in an app after wagtailstreamforms in INSTALLED_APPS. Another alternative would be to fork the repo and install it from the git url.

Cheers
Stu
