### ISSUE TITLE
Conflict in form field names that prevent them from appearing in the template

### ISSUE THREAD

**Issue by vinodMS** [labd/wagtailstreamforms#140]
### Expected behaviour
Create two form fields with the same name and have them displayed in the template.

### Actual behaviour
Only one of the fields appear in the template.

### Steps to reproduce the behaviour
Create two form fields with the same name.

In the template add the following code,
```
{% for field in form.visible_fields %}
  {{ field }}
{% endfor %}
```
and then verify in the browser if both fields are being shown.

**Comment by vinodMS** [comment]
Here's what's causing this behavior. the formfields property in the FormBuilder class is of type OrderedDict. The key used to store each field in the orderedDict is the label name. So having two fields with the same label name ends up in the first item in the dictionary being reassigned to the second field value. 

https://github.com/labd/wagtailstreamforms/blob/f78226bbf55a784093a2cf9cd612dec4678e753a/wagtailstreamforms/forms.py#L50

I guess we should use a unique key to make sure fields are not reassigned. But it's not that simple, as this will have an effect on the form submissions.

**Comment by rgs258** [comment]
Hi,

We did exactly this and are using the streamfield id as the form field name. It works quite well.
