### ISSUE TITLE
Allow fields to have defined name instead built from label

### ISSUE THREAD

**Issue by Quadric** [labd/wagtailstreamforms#142]
I use that app for some time and always trying to figure out why there are no dedicated value for "name" of field and instead it is generated from label. For most cases i use that app it's not enough.

### Expected behaviour

I'd like to have field with it's defined "name" attribute instead generated from field label.

```
    <label for="id_phone">
        Phone Number
    </label>
    <input name="phone" type="text" id="id_phone">
```
            
### Actual behaviour

```
    <label for="id_phone-number">
        Phone Number
    </label>
    <input name="phone-number" type="text" id="id_phone-number">
```

### Steps to reproduce the behaviour

Just add any field to form and you'll see above HTML syntax

### Why?

For ex.: i need to create a "login form" as a "frontend" based on StreamBlock on my Page. I'd like to reuse original django view support for login procedure (changed to ajax mode) instead reinventing the wheel. Login procedure use a LoginForm with "username" and "password" fields. My goal is to create many fully configurable login forms (and other) in many languages (so i need different form labels) but have on "backend" for login procedure - so my field names must be known and predictable... my different labels for "first name" in other languages ("First name", "Imię", "Name", "имя", "名前") or other cases like changing label "First name" to "Your first name"... all of that cases must lead to fact that field has a name "first_name" so i can use predictable values to handle it correctly.

### Problem

Field names are generated in "FormBuilder" class which is not easy to switch or modify

```python
                # slugify the label for the field name
                field_name = get_slug_from_string(field_value.get('label'))
```

So i don't see any possibility to easily overwrite this behaviour (instead of monkey patching).

As in documentation it is written how to:
1) set editable field options (max-length example) - for my case it would be "name"
2) use ajax frontend handling and backend overwrite (for my case this would be django login view)

but there is no possibility to use that additional "field option" for field own name

### My recommendation/solution

The easiest way is to upgrade FormBuilder to use "field_name" from "name" value defined in field options... then if param does not exists or is empty use (as a fallback) value generated from label.

before:

```
            # slugify the label for the field name
            field_name = get_slug_from_string(field_value.get('label'))
```

after

```python
            field_name = field_value.get('name')
            if not field_name:
                # slugify the label for the field name
                field_name = get_slug_from_string(field_value.get('label'))
```

does make sense?

**Comment by ayushin** [comment]
Took the liberty to implement it https://github.com/labd/wagtailstreamforms/pull/149
