### ISSUE TITLE
Best way to make form input groups?

### ISSUE THREAD

**Issue by gwenf** [labd/wagtailstreamforms#153]
I want to create input groups for forms that look like this:
<img width="740" alt="Screen Shot 2020-08-18 at 9 19 41 PM" src="https://user-images.githubusercontent.com/10039233/90581266-d13dfa80-e198-11ea-940d-03b3cff6ed1b.png">

I would like to be able to select an input type of input group and then customize each input.
I'm having a hard time figuring out the best way to do this. If you can point me in the right direction, I would appreciate it. Thanks.

**Comment by rgs258** [comment]
@gwenf , we solved this issue using the [MultiValueField](https://docs.djangoproject.com/en/3.1/ref/forms/fields/#multivaluefield) and MultiWidget. Basically, you build a new form field from MultiValueField and include all your group fields, then you render it as you like using the MultiWidget.

Sorry it took so long to respond. I hope this helps!

**Comment by gwenf** [comment]
Thanks @rgs258! Yes.
