### ISSUE TITLE
Add support for wagtail 2.11 and future higher version

### ISSUE THREAD

**Issue by lingster** [labd/wagtailstreamforms#158]
If using pipenv and attempting to install wagtailstreamforms with latest wagtail 2.11 version, it refuses due to dependency issue.

latest wagtail version should be fine to work with latest wagtailstreamforms version

**Comment by nnist** [comment]
I've merged your PR (#159) but it seems to break a few things. The docs suggest to remove 'wagtail.core.middleware.SiteMiddleware' which I tried, but a few test still fail. I'm a bit short on time to work on this right now, but I'll look into it further when I can.

**Comment by lingster** [comment]
hi, thanks for the reply, I'll try to find sometime this week to see if I can resolve the issues you've raised.

**Comment by funkhaus-phil** [comment]
https://docs.wagtail.io/en/stable/releases/2.9.html
this might help you from the release notes of version 2.9:

SiteMiddleware and request.site deprecated
Wagtail’s SiteMiddleware, which makes the current site object available as the property request.site, is now deprecated as it clashes with Django’s sites framework and makes unnecessary database queries on non-Wagtail views. References to request.site in your code should be removed; the recommended way of retrieving the current site is Site.find_for_request(request) in Python code, and the {% wagtail_site %} tag within Django templates.

For example:

# old version

def get_menu_items(request):
    return request.site.root_page.get_children().live()

# new version

from wagtail.core.models import Site

def get_menu_items(request):
    return Site.find_for_request(request).root_page.get_children().live()
{# old version #}

<h1>Welcome to the {{ request.site.site_name }} website!</h1>


{# new version #}
{% load wagtailcore_tags %}
{% wagtail_site as current_site %}

<h1>Welcome to the {{ current_site.site_name }} website!</h1>
Once these are removed, 'wagtail.core.middleware.SiteMiddleware' can be removed from your project’s MIDDLEWARE setting.

**Comment by funkhaus-phil** [comment]
@nnist this was fixed in #161 please merge and release this commits. otherwise it is not possible to use wagtailstreamforms in up to date projects

**Comment by nnist** [comment]
@funkhaus-phil Thanks for bringing it to my attention. #161 is now merged, I'll create a new release in a moment.
