### ISSUE TITLE
Support for Wagtail 2.12

### ISSUE THREAD

**Issue by betimd** [labd/wagtailstreamforms#167]
We want to have power of wagtailstreamforms for forms creation and management into our product, but while we're a dynamic team we upgraded wagtail to new version (2.21.2) and it seems wtsf is not supporting it yet - it's downgrading wt when we pip install.

Do we have any estimation when wagtail 2.12 is going to be supported?

Or is there a workaround to skip downgrading of wagtail when we pip install wagtailstreamform?

**Comment by nnist** [comment]
Wagtail 2.12 support has been added in version [3.14.0](https://github.com/labd/wagtailstreamforms/releases/tag/3.14.0) which was released on Mar 26.
