### ISSUE TITLE
Releasing version for Wagtail 2.15 and pypi homepage link

### ISSUE THREAD

**Issue by samastur** [labd/wagtailstreamforms#186]
When can we expect version 3.17 supporting Wagtail 2.15 to be released?

Also, on the [pypi page](https://pypi.org/project/wagtailstreamforms/) homepage links to a fork of this repo, which seems to update from this one.

**Comment by kfields** [comment]
Yes, please.  I was excited to try this out.  ETA would be appreciated!

**Comment by leongraumans** [comment]
Hi, just released version 3.17, apologies for the delay!

**Comment by samastur** [comment]
Thanks and thank you for the wagtailstreamforms.
