### ISSUE TITLE
Update for Wagtail 2.16.x and Django 4.0

### ISSUE THREAD

**Issue by funkhaus-phil** [labd/wagtailstreamforms#189]
Hello lovely wagtailstreamforms people,

Wagtail released version 2.16.x wich supports Django 4.0.x
First of all this project does not support the new Wagtail release yet which would be very nice.
When thats working it would be fantastic if Django 4.0.x would be supported as well, since there are some changes on djangos site as well that break the project.

Here are the errors i am encountering while trying a fully updated environment:

Wagtail:
`ERROR: wagtailstreamforms 3.17 has requirement wagtail<2.16,>=2, but you'll have wagtail 2.16.1 which is incompatible.`

Django:
```
site-packages/wagtailstreamforms/models/file.py", line 3, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation'
```

**Comment by ZhdanDesign** [comment]
I tried to rewrite the some code for this very problem. It works, but badly... [https://github.com/ZhdanDesign/wagtailstreamforms_D4WT2]

**Comment by funkhaus-phil** [comment]
@ZhdanDesign might have been better to add to this project instead of opening an own one since people are actively working on it.

it seems you got the same issue as me and are looking for a hotfix. here is my suggestion for you even tho it's not the recommended way to handle upgrades:
if you need an integration in your own updated system it might be okay to not use django 4.0.x, but wagtail 2.16.x, yet and use the legacy pip installation process for your requirements or the new one if that does not abort your installation process.
this way you have no actual errors, the package is working and all you get is a warning that your version of wagtailstreamforms is not supported. just like in this screenshot:
![Bildschirmfoto 2022-03-02 um 21 06 40](https://user-images.githubusercontent.com/74963047/156442075-bb1aaa22-c6d3-4c64-b3af-b61f0e51edef.png)
