### ISSUE TITLE
Django 3.2.19 breaks package

### ISSUE THREAD

**Issue by jasonmishi** [labd/wagtailstreamforms#215]
### Expected behaviour
Package to work with Django 3.2

### Actual behaviour
Breaks because of this section of code: https://github.com/labd/wagtailstreamforms/blob/b32bf28f97b0ee54b79515005a15cedfe74510a7/wagtailstreamforms/wagtailstreamforms_fields.py#L217
Caused by change in django 3.2.19: https://docs.djangoproject.com/en/4.2/releases/3.2.19/

### Steps to reproduce the behaviour
It seems like the automated testing has picked this up (https://github.com/labd/wagtailstreamforms/actions/runs/4910029700/jobs/8766814912#step:6:58) but possibly failed to alert the error because of: https://github.com/labd/wagtailstreamforms/actions/runs/4910029700/workflow#L40

**Comment by MichielBijland** [comment]
This is probably fixed with latest release
